version: "3"

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  web:
    build: .
    command: uvicorn xoxo.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    depends_on:
      - web

volumes:
  postgres_data:
